import { z } from "zod";

export const videoStyleSchema = z.enum([
  "ke-chuyen",
  "kien-thuc",
  "truyen-cam-hung",
  "meo-cuoc-song",
]);

export const aspectRatioSchema = z.enum(["9:16", "1:1", "16:9"]);
export const generationPresetSchema = z.enum(["fast", "balanced", "quality"]);
export const visualPresetSchema = z.enum([
  "cinematic-color",
  "ink-monochrome",
  "cartoon",
  "historical",
  "watercolor",
  "paper-cut",
  "whiteboard",
  "chibi-co-phong",
]);
export type VisualPreset = z.infer<typeof visualPresetSchema>;
export const projectStatusSchema = z.enum([
  "draft",
  "generating_media",
  "queued",
  "rendering",
  "completed",
  "failed",
]);

export const subtitleStyleSchema = z.object({
  enabled: z.boolean().default(true),
  preset: z.enum(["classic", "focus", "minimal"]).default("classic"),
  position: z.enum(["top", "center", "bottom"]).default("bottom"),
  fontColor: z
    .string()
    .regex(/^#[0-9A-Fa-f]{6}$/)
    .default("#FFFFFF"),
  outlineColor: z
    .string()
    .regex(/^#[0-9A-Fa-f]{6}$/)
    .default("#101828"),
  backgroundColor: z
    .string()
    .regex(/^#[0-9A-Fa-f]{6}$/)
    .default("#000000"),
  backgroundOpacity: z.number().min(0).max(1).default(0.35),
});

export const logoPositionSchema = z.enum(["top-left", "top-center", "top-right", "bottom-left", "bottom-right"]);

/** full-bleed: ảnh phủ toàn khung. story-card: tiêu đề + dải tranh + phụ đề + chữ ký kênh trên nền màu (kiểu video truyện minh họa). */
// paper-stage: one character on plain kraft paper, caption under it ("Đạo lý cổ phong" shorts).
export const layoutTemplateSchema = z.enum(["full-bleed", "story-card", "paper-stage"]);

export const subtitleCueSchema = z
  .object({
    id: z.string().uuid(),
    startMs: z.number().int().min(0),
    endMs: z.number().int().positive(),
    text: z.string().min(1).max(240),
  })
  .refine((cue) => cue.endMs > cue.startMs, {
    message: "Thoi diem ket thuc phai sau thoi diem bat dau",
  });

export const sceneSchema = z.object({
  id: z.string().uuid(),
  order: z.number().int().min(0),
  narration: z.string().min(1).max(2000),
  imagePrompt: z.string().min(1).max(3000),
  estimatedDurationMs: z.number().int().min(1000).max(120000),
  actualDurationMs: z
    .number()
    .int()
    .min(100)
    .max(180000)
    .nullable()
    .default(null),
  imagePath: z.string().nullable().default(null),
  /** Optional motion clip generated by a local image-to-video model. */
  videoPath: z.string().nullable().default(null),
  audioPath: z.string().nullable().default(null),
  thumbnailUrl: z.string().url().nullable().default(null),
  mediaStatus: z
    .enum(["pending", "processing", "ready", "failed"])
    .default("pending"),
  errorMessage: z.string().nullable().default(null),
  subtitles: z.array(subtitleCueSchema).default([]),
  /** Annotation JSON for whiteboard animation (regions, timing, draw order). */
  annotationJson: z.unknown().nullable().default(null),
});

const localModelName = z
  .string()
  .regex(/^[\w.:/-]{1,100}$/u, "Tên model không hợp lệ")
  .nullable()
  .default(null);

/** Model AI chạy trên máy theo từng tác vụ; null = dùng mặc định của máy. */
export const localModelsSchema = z.object({
  storyboard: localModelName,
  image: localModelName,
  video: localModelName,
  tts: localModelName,
  transcribe: localModelName,
});
export type LocalModels = z.infer<typeof localModelsSchema>;
export const DEFAULT_LOCAL_MODELS: LocalModels = {
  storyboard: null,
  image: null,
  video: null,
  tts: null,
  transcribe: null,
};

export const projectSettingsSchema = z.object({
  textProvider: z.enum(["anthropic", "openai", "ollama"]).default("anthropic"),
  mediaProvider: z.enum(["local", "openai"]).default("local"),
  targetAudience: z.string().max(500).default("Người xem Việt Nam"),
  style: videoStyleSchema.default("ke-chuyen"),
  // Length of the video written from an idea (packages/shared/src/duration.ts DURATION_OPTIONS).
  targetDurationSec: z
    .union([z.literal(15), z.literal(30), z.literal(45), z.literal(60), z.literal(90), z.literal(120), z.literal(180)])
    .default(60),
  aspectRatio: aspectRatioSchema.default("9:16"),
  generationPreset: generationPresetSchema.default("balanced"),
  visualPreset: visualPresetSchema.default("cinematic-color"),
  voice: z.string().default("alloy"),
  localModels: localModelsSchema.default(DEFAULT_LOCAL_MODELS),
  visualStyle: z.string().max(500).default("Ảnh điện ảnh chân thực, ánh sáng tự nhiên, nhân vật Việt Nam"),
  allowUploads: z.boolean().default(true),
  backgroundMusicPath: z.string().nullable().default(null),
  musicVolume: z.number().min(0).max(0.5).default(0.12),
  logoPath: z.string().nullable().default(null),
  logoPosition: logoPositionSchema.default("top-right"),
  logoScale: z.number().min(0.05).max(0.35).default(0.14),
  logoOpacity: z.number().min(0.1).max(1).default(0.9),
  rewriteFullScript: z.boolean().default(false),
  layoutTemplate: layoutTemplateSchema.default("full-bleed"),
  /** Tiêu đề in hoa trên đầu thẻ truyện; để trống để tự viết từ kịch bản. */
  cardTitle: z.string().max(80).default(""),
  /** Tên kênh in ở chân thẻ truyện ("Bản quyền thuộc về: …"). */
  brandName: z.string().max(60).default(""),
  /** Tốc độ đọc: 1 = bình thường; kênh suy ngẫm thường đọc nhanh hơn (≈1.15-1.25). */
  voiceSpeed: z.number().min(0.8).max(1.3).default(1),
  /** Tự tạo nhạc nền êm khi chưa tải nhạc riêng. */
  autoMusic: z.boolean().default(false),
  /** Captions light up word by word as they are spoken (karaoke style). */
  captionHighlight: z.boolean().default(false),
  /** Big title over the first seconds of a full-frame video (the story card already has a title banner). */
  hookTitle: z.boolean().default(false),
  trimSilence: z.boolean().default(false),
  subtitle: subtitleStyleSchema.default({
    enabled: true,
    preset: "classic",
    position: "bottom",
    fontColor: "#FFFFFF",
    outlineColor: "#101828",
    backgroundColor: "#000000",
    backgroundOpacity: 0.35,
  }),
});

export const projectSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  title: z.string().min(1).max(160),
  sourceText: z.string().min(1).max(30000),
  inputMode: z.enum(["idea", "full-script", "srt"]).default("idea"),
  hook: z.string().max(500).default(""),
  suggestedTitle: z.string().max(200).default(""),
  suggestedDescription: z.string().max(2000).default(""),
  status: projectStatusSchema.default("draft"),
  settings: projectSettingsSchema,
  scenes: z.array(sceneSchema).default([]),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

export const createProjectSchema = z.object({
  title: z.string().trim().min(1, "Vui lòng nhập tên video").max(160),
  sourceText: z
    .string()
    .trim()
    .min(10, "Ý tưởng hoặc kịch bản cần ít nhất 10 ký tự")
    .max(30000),
  inputMode: z.enum(["idea", "full-script", "srt"]).default("idea"),
  settings: projectSettingsSchema,
});

export const createVideoSchema = z.object({
  sourceText: z.string().min(10).max(30000).refine((text) => text.trim().length >= 10, {
    message: "Kịch bản cần ít nhất 10 ký tự",
  }),
  inputMode: z.enum(["idea", "full-script", "srt"]).default("full-script"),
  settings: projectSettingsSchema.partial().default({}),
});

export const updateProjectSchema = z.object({
  title: z.string().trim().min(1).max(160).optional(),
  sourceText: z.string().trim().min(1).max(30000).optional(),
  hook: z.string().max(500).optional(),
  suggestedTitle: z.string().max(200).optional(),
  suggestedDescription: z.string().max(2000).optional(),
  settings: projectSettingsSchema.partial().optional(),
});

export const updateSceneSchema = sceneSchema
  .pick({
    narration: true,
    imagePrompt: true,
    subtitles: true,
  })
  .partial();

export const jobSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string().uuid(),
  type: z.enum([
    "create_video",
    "storyboard",
    "generate_media",
    "regenerate_scene",
    "render_video",
    "dub_video",
    "render_whiteboard",
  ]),
  status: z.enum(["queued", "running", "completed", "failed", "cancelled"]),
  progress: z.number().int().min(0).max(100),
  stage: z.string(),
  errorMessage: z.string().nullable(),
  attempts: z.number().int().min(0),
  maxAttempts: z.number().int().min(1),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

export const estimateSchema = z.object({
  imageCount: z.number().int().min(0),
  narrationCharacters: z.number().int().min(0),
  transcriptionMinutes: z.number().min(0),
  estimatedUsd: z.number().min(0),
  note: z.string(),
});

export type Project = z.infer<typeof projectSchema>;
export type Scene = z.infer<typeof sceneSchema>;
export type ProjectSettings = z.infer<typeof projectSettingsSchema>;
export type Job = z.infer<typeof jobSchema>;
export type Estimate = z.infer<typeof estimateSchema>;
